export const ERROR_MESSAGES = {
    INVALID_NAME: "Nome inválido",
    INVALID_EMAIL: "E-mail inválido",
    INVALID_AGE: "Idade inválida",
    INVALID_CPF: "CPF inválido",
    INVALID_PHONE: "Telefone inválido",
    INVALID_SERASA_PF_SCORE: "Score do Serasa PF inválido",
    INVALID_COMPANY_NAME: "Nome da empresa inválido",
    INVALID_BUSINESS_AREA: "Área de negócio inválida",
    INVALID_CNPJ: "CNPJ inválido",
    INVALID_FOUNDATION_YEARS: "Anos de fundação inválidos",
    INVALID_SOCIAL_CAPITAL: "Capital social inválido",
    INVALID_SERASA_COMPANY_SCORE: "Score do Serasa da empresa inválido",
    INVALID_ANNUAL_REVENUE: "Receita anual inválida",
    CLIENT_NOT_FOUND: "Cliente não encontrado",
    ERROR_RETRIEVING_CLIENTS: "Erro ao recuperar clientes",
    ERROR_RETRIEVING_ELIGIBILITY_DATA: "Erro ao recuperar dados de elegibilidade",
    ERROR_ADDING_CLIENT: "Erro ao adicionar cliente",
    ERROR_UPDATING_CLIENT: "Erro ao atualizar cliente",
    ERROR_UPDATING_CNPJ: "Erro ao atualizar o CNPJ do cliente",
    ERROR_DELETING_CLIENT: "Erro ao excluir cliente",
    ERROR_DELETING_CLIENTS: "Erro ao excluir os clientes",
  };
  